#File application.yaml là những config chung cho cái service

server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "kgVcXjhib3Tvrb+k5SYM9taZzeGxup6VkTM23IHCHC+MI/xH5t7xvdk4aoThe7Qy"
  valid-duration: 20 #in seconds
  refreshable-duration: 120 #in seconds